windowsExporter:
  image:
    repository: ghcr.io/prometheus-community/windows-exporter
    tag: latest
  config:
    collectors:
      enabled: '[defaults],ad,adfs,cache,cpu,cpu_info,cs,container,dfsr,dhcp,dns,fsrmquota,iis,logical_disk,logon,memory,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,process,remote_fx,service,tcp,time,vmware'
      pod:
        kubeletPort: 10255
    collector:
      service:
        services-where: "Name='containerd' or Name='kubelet'"

service:
  type: LoadBalancer
  name: windows-exporter-service
  port: 9182
  targetPort: 9182
