apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.service.namespace }}
  labels:
    app: windows-exporter
spec:
  selector:
    app: windows-exporter
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: {{ .Values.service.type }}
